Worklenz/worklenz

docker-compose.yml
This pull request adds the `networks` configuration to the `docker-compose.yml` file to ensure consistent networking across all services.
=> adding network configuration to docker-compose file

README.md, start.sh, stop.sh
- Changed repository URLs in README.md.
- Enhanced start.sh with a service health check function to verify if services are running and responding.
- Improved output messages in start.sh and stop.sh.
- Added checks for port conflicts and ensured proper stopping of services in stop.sh.
=> Update README.md and scripts for improved setup and service management

worklenz-backend/src/interfaces/socket-session.ts, worklenz-backend/src/socket.io/util.ts
- Changed the user structure in ISocketSession to include an object with an 'id' property.
- Updated the getLoggedInUserIdFromSocket function to return the user ID directly from the new structure.
=> Refactor socket session user structure and update user ID retrieval

README.md, docker-compose.yml, update-docker-env.sh, worklenz-frontend/Dockerfile, worklenz-frontend/src/config/env.ts, worklenz-frontend/src/socket/config.ts
- Added VITE_SOCKET_URL to docker-compose.yml for WebSocket connection.
- Updated update-docker-env.sh to handle SSL options for WebSocket URLs.
- Modified Dockerfile to include VITE_SOCKET_URL in env-config.js.
- Implemented getSocketUrl function in frontend to retrieve WebSocket URL.
- Refactored socket configuration to use centralized socket URL from environment settings.
=> Enhance WebSocket support and update environment configuration

update-docker-env.sh, worklenz-backend/src/app.ts
- Updated update-docker-env.sh to define FRONTEND_URL and streamline CORS settings.
- Modified app.ts to include SERVER_CORS and FRONTEND_URL in allowed origins for both production and development environments.
- Improved output messages in update-docker-env.sh to provide clearer information on URLs and CORS configuration.
=> Enhance environment configuration for frontend and CORS support

docker-compose.yml
- Changed the frontend service to build from a local context instead of using a pre-built image.
- Specified the Dockerfile for the frontend build process.
=> Refactor frontend service configuration in docker-compose.yml

worklenz-frontend/Dockerfile
- Updated the Dockerfile to create the start.sh script in a more structured manner, improving readability and maintainability.
- Ensured that the script dynamically updates env-config.js with runtime environment variables for API and WebSocket URLs.
=> Refactor start.sh script creation in Dockerfile

worklenz-frontend/Dockerfile
- Introduced a new env-config.sh script to handle runtime environment variable updates for VITE_API_URL and VITE_SOCKET_URL.
- Updated start.sh to execute env-config.sh, improving script organization and clarity.
- Enhanced the overall structure of the Dockerfile for better maintainability.
=> Refactor Dockerfile to streamline environment configuration

worklenz-frontend/public/locales/en/task-drawer/task-drawer.json, worklenz-frontend/public/locales/es/task-drawer/task-drawer.json, worklenz-frontend/public/locales/pt/task-drawer/task-drawer.json, worklenz-frontend/src/components/task-drawer/shared/info-tab/details/task-drawer-progress/task-drawer-progress.tsx, worklenz-frontend/src/components/task-drawer/task-drawer-status-dropdown/task-drawer-status-dropdown.tsx
- Introduced new localization entries for task progress confirmation prompts in English, Spanish, and Portuguese, enhancing user experience.
- Updated frontend components to utilize localized strings for task completion modals, ensuring consistency across languages.
- Implemented logic to restrict task progress input to a maximum of 100%, improving data integrity and user feedback during task updates.
=> Add task progress confirmation prompts and localization updates

worklenz-backend/database/migrations/consolidated-progress-migrations.sql, worklenz-backend/src/controllers/admin-center-controller.ts, worklenz-frontend/src/api/admin-center/admin-center.api.service.ts, worklenz-frontend/src/components/admin-center/teams/settings-drawer/settings-drawer.tsx
- Refactored the team update function in the Admin Center controller to improve error handling and response messages.
- Implemented concurrent updates for team member roles using Promise.all, enhancing performance and user experience.
- Updated the frontend API service to accept a structured body for team updates, ensuring consistency in data handling.
- Enhanced the settings drawer component to manage team member roles more effectively, improving the overall user interface.
=> Enhance team update logic and error handling

worklenz-backend/src/controllers/admin-center-controller.ts, worklenz-frontend/public/locales/en/admin-center/teams.json, worklenz-frontend/public/locales/es/admin-center/teams.json, worklenz-frontend/public/locales/pt/admin-center/teams.json, worklenz-frontend/src/components/admin-center/teams/settings-drawer/settings-drawer.tsx, worklenz-frontend/src/types/admin-center/admin-center.types.ts
- Added a new SQL field to indicate pending invitations for team members, improving role management logic.
- Updated the settings drawer component to display tooltips for roles that cannot be changed, enhancing user experience.
- Introduced new localization entries for pending invitations and role change restrictions in English, Spanish, and Portuguese, ensuring consistency across languages.
=> Enhance team member role management and localization updates

worklenz-frontend/src/pages/projects/projectView/taskList/project-view-task-list.tsx
- Introduced a local loading state to improve user experience by displaying a skeleton loader while data is being fetched.
- Refactored data loading logic to utilize Promise.all for concurrent dispatching of task-related data, ensuring efficient data retrieval.
- Updated the rendering logic to conditionally display the skeleton loader based on the new loading state, enhancing UI responsiveness.
=> Enhance task list loading state management

worklenz-backend/.env.template, worklenz-backend/src/shared/constants.ts
- Modified the .env.template to separate AWS SES and S3 configurations, adding new environment variables for S3 region and access keys.
- Updated constants.ts to reflect changes in environment variable names for S3, ensuring consistency in accessing S3 credentials.
=> refactor(env): update AWS configuration for S3 integration

worklenz-frontend/index.html
- Modified the Microsoft Clarity script in index.html to use a hardcoded tracking ID instead of relying on the VITE_CLARITY_ID environment variable. This change ensures consistent tracking on the app.worklenz.com domain.
=> fix(index.html): update Microsoft Clarity integration for tracking

worklenz-frontend/jest.config.js, worklenz-frontend/postcss.config.js, worklenz-frontend/tailwind.config.js
- Updated jest.config.js, postcss.config.js, and tailwind.config.js to use CommonJS module.exports syntax for compatibility with Node.js environments.
=> refactor(config): switch configuration files to CommonJS module syntax

worklenz-frontend/src/components/task-management/improved-task-filters.tsx
- Updated useFilterData to support both board and list views, utilizing enhanced Kanban state for filtering.
- Integrated new selectors for Kanban-specific filters including priorities, labels, and assignees.
- Refactored handleSelectionChange and handleSearchChange to accommodate Kanban logic, ensuring proper dispatch of actions based on the selected view.
- Improved overall filter functionality and user experience in task management.
=> feat(task-filters): enhance ImprovedTaskFilters for Kanban integration

worklenz-frontend/src/components/task-management/task-row.tsx
- Introduced a visual indicator for task progress, displaying a CheckCircle icon when progress reaches 100%.
- Updated the rendering logic to show a progress bar for incomplete tasks, enhancing user feedback on task status.
=> feat(task-row): add progress indicator with CheckCircle icon

worklenz-frontend/src/components/enhanced-kanban/EnhancedKanbanBoardNativeDnD/KanbanGroup.tsx
- Introduced a Portal component to render the delete confirmation modal outside the main DOM hierarchy, improving UI responsiveness.
- Updated the delete confirmation modal to utilize the Portal for better overlay management and user experience.
- Enhanced styling and interaction handling for the modal, ensuring it aligns with the application's theme and accessibility standards.
=> feat(kanban): implement portal for delete confirmation modal

worklenz-frontend/src/components/AssigneeSelector.tsx, worklenz-frontend/src/components/enhanced-kanban/EnhancedKanbanBoardNativeDnD/TaskCard.tsx
- Introduced kanbanMode prop to AssigneeSelector for improved functionality in kanban view.
- Updated styling in AssigneeSelector to adjust z-index for better overlay management.
- Enhanced TaskCard to include LazyAssigneeSelectorWrapper, integrating the new prop for task assignment in kanban mode.
=> feat(assignee-selector): add kanbanMode prop and enhance styling

worklenz-frontend/public/locales/alb/kanban-board.json, worklenz-frontend/public/locales/de/kanban-board.json, worklenz-frontend/public/locales/en/kanban-board.json, worklenz-frontend/public/locales/es/kanban-board.json, worklenz-frontend/public/locales/pt/kanban-board.json, worklenz-frontend/public/locales/zh/kanban-board.json, worklenz-frontend/src/components/enhanced-kanban/EnhancedKanbanBoardNativeDnD/EnhancedKanbanBoardNativeDnD.tsx, worklenz-frontend/src/features/enhanced-kanban/enhanced-kanban.slice.ts, worklenz-frontend/src/hooks/useTaskSocketHandlers.ts, worklenz-frontend/src/pages/projects/projectView/board/project-view-board.tsx, worklenz-frontend/src/utils/enhanced-performance-monitoring.ts
- Integrated phase reordering functionality within the EnhancedKanbanBoardNativeDnD component.
- Added logic to fetch phases by project ID and update phase order through API calls.
- Updated drag-and-drop handling to accommodate reordering of phases alongside existing status-based reordering.
=> Enhance EnhancedKanbanBoardNativeDnD to support phase reordering

worklenz-backend/database/sql/indexes.sql
- Introduced multiple new indexes in the SQL schema to enhance query performance for tasks, including composite indexes for filtering and sorting.
- Added indexes for various task-related entities such as assignees, phases, labels, comments, and attachments to improve data retrieval efficiency.
- Implemented covering indexes to optimize task aggregation and search functionalities, ensuring faster access to frequently queried data.
=> feat(database): add performance indexes for optimized task queries
